name:                proto-purescript
version:             0.1.0.0
github:              "githubuser/proto-purescript"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/proto-purescript#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  proto-purescript-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options: -Wall -O2 -fno-warn-unused-do-bind -threaded -rtsopts -with-rtsopts=-N
    other-modules:
      - Version
      - MainTest
    dependencies:
    - optparse-applicative >=0.13.0
    - proto-purescript
    when:
    - condition: flag(release)
      then:
        cpp-options: -DRELEASE
      else:
        dependencies:
        - gitrev >=1.2.0 && <1.4

tests:
  proto-purescript-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - proto-purescript

flags:
  release:
    description: >
        Mark this build as a release build: prevents inclusion of extra
        info e.g. commit SHA in --version output)
    manual: false
    default: false
